name: Integrate

on:
  pull_request:
  push:

jobs:
  composer-normalize:
    strategy:
      matrix:
        php: [8.1, 8.2]

    name: Composer normalize (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine Composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --optimize-autoloader --ansi --no-interaction

      - name: Validate composer.json
        run: composer normalize --dry-run --ansi --diff

  composer-validate:
    strategy:
      matrix:
        php: [8.1]

    name: Composer validate (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine Composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Validate composer.json
        run: composer validate --strict

  php-cs-fixer:
    strategy:
      matrix:
        php: [8.1]

    name: PHP CS Fixer (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine Composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --optimize-autoloader --ansi --no-interaction

      - name: Run PHP CS Fixer
        run: composer fixcs -- --dry-run --ansi --diff --format=checkstyle | cs2pr

  psalm:
    strategy:
      matrix:
        php: [8.1]

    name: Psalm (PHP ${{ matrix.php }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine Composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Run Psalm
        run: composer psalm -- --stats --long-progress --output-format=github --php-version=${{ matrix.php }}
